[build]
  command = "echo 'No build step required'"
  publish = "./team-selection-app"

[functions]
  directory = "team-selection-app/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npx serve team-selection-app"
  port = 3000
  publish = "team-selection-app"
  functions = "team-selection-app/netlify/functions"
